### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nlw0**
Help a newbie out

### CODE REVIEW

**Comment by pinx** [comment]
Thanks for your contribution.
Could you add a bit of explanation in the readme, or in the `cgconfig.ocnf`, so newbies know why we set this memory limit, and what could be reasons to increase or decrease this number.

**Comment by nlw0** [comment]
Oops, sorry about that, I just wanted to merge the very first commit about how to run the buildset configuration command... After that I've been looking for a way to limit memory usage but it didn't work yet. Do you have any ideas for that? I cannot even compile a package on the free heroku Dyno. Maybe paying is perhaps the best solution, beta anyways...

**Comment by pinx** [comment]
Sorry, I only used it on dokku. You could contact one of the other contributors, to see if they have experience with this issue. It seemed some of your other changes were valuable, so feel free to push those.

**Comment by nlw0** [comment]
I am not really sure the other stuff I did was really necessary or useful... I moved away from Heroku for the moment, so it's hard for me to evaluate this properly. But just having the full command in the README would have saved me a few minutes!

**Pull request merged**
